name: Convert & Push Mihomo MRS to Repo Root

on:
  workflow_dispatch:
    # No inputs needed as all parameters are hardcoded for this specific conversion
  push:
    paths:
      - 'privateDomain.yaml'
    

jobs:
  convert-and-push-ruleset:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许上传 Artifacts 和向仓库写入

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          fetch-depth: 0 

      - name: Get Latest Mihomo Release Tag via API
        id: get_release_tag # Assign an ID to this step to access its outputs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure GH_TOKEN is available for gh CLI
        run: |
          LATEST_TAG=$(gh api /repos/MetaCubeX/mihomo/releases/latest --jq .tag_name)
          if [ -z "$LATEST_TAG" ]; then
            echo "Error: Could not retrieve latest release tag from MetaCubeX/mihomo."
            exit 1
          fi
          echo "Latest Mihomo Release Tag: $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"

      - name: Determine download pattern and download Mihomo (Linux AMD64 .gz)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SELECTED_OS: linux
          SELECTED_ARCH: amd64
          MIHOMO_RELEASE_TAG: ${{ steps.get_release_tag.outputs.tag }} # Use the output from the previous step
        run: |
          DOWNLOAD_PATTERN="mihomo-${SELECTED_OS}-${SELECTED_ARCH}-${MIHOMO_RELEASE_TAG}.gz" 
          
          echo "Attempting to download assets matching: $DOWNLOAD_PATTERN"
          
          mkdir -p ./mihomo-downloads

          # Now, use the obtained tag name for downloading specific assets
          gh release download \
            --repo MetaCubeX/mihomo \
            --pattern "$DOWNLOAD_PATTERN" \
            --dir ./mihomo-downloads \
          
          echo "Downloaded files:"
          ls -l ./mihomo-downloads/

      - name: Unpack Mihomo executable (gunzip) and set permissions
        id: unpack_mihomo
        env:
          SELECTED_OS: linux
          SELECTED_ARCH: amd64
        run: |
          DOWNLOAD_DIR="./mihomo-downloads"
          GZ_FILE=""
          MIHOMO_EXECUTABLE_PATH=""
          
          GZ_FILE=$(find "$DOWNLOAD_DIR" -maxdepth 1 -name "mihomo-${SELECTED_OS}-${SELECTED_ARCH}*.gz" -print -quit)
          
          if [ -z "$GZ_FILE" ]; then
            echo "Error: Mihomo GZ file not found for ${SELECTED_OS}/${SELECTED_ARCH} in $DOWNLOAD_DIR"
            exit 1
          fi
          
          echo "Decompressing GZ file: $GZ_FILE"
          gunzip "$GZ_FILE"
          
          MIHOMO_EXECUTABLE_PATH=$(find "$DOWNLOAD_DIR" -maxdepth 1 -name "mihomo-${SELECTED_OS}-${SELECTED_ARCH}*" -type f -a ! -name "*.gz" -print -quit)
          
          if [ -z "$MIHOMO_EXECUTABLE_PATH" ]; then
            echo "Error: Mihomo executable not found after decompression in $DOWNLOAD_DIR"
            exit 1
          fi
          
          echo "Setting execute permission for: $MIHOMO_EXECUTABLE_PATH"
          chmod +x "$MIHOMO_EXECUTABLE_PATH"
          
          echo "MIHOMO executable path determined as: $MIHOMO_EXECUTABLE_PATH"
          echo "mihomo_path=$MIHOMO_EXECUTABLE_PATH" >> "$GITHUB_OUTPUT"

      - name: Convert Ruleset using Mihomo
        run: |
          MIHOMO_BIN="${{ steps.unpack_mihomo.outputs.mihomo_path }}"
          INPUT_FILE="${{ github.workspace }}/privateDomain.yaml" # Assumed in repo root
          TEMP_OUTPUT_DIR="temp-mihomo-output"
          TEMP_OUTPUT_FILE="$TEMP_OUTPUT_DIR/privateDomain.mrs"
          
          mkdir -p "$TEMP_OUTPUT_DIR"
          
          if [ ! -f "$INPUT_FILE" ]; then
            echo "Error: Input file '$INPUT_FILE' not found in your repository's root directory."
            echo "Please ensure 'privateDomain.yaml' exists directly in the repository's root."
            exit 1
          fi
          
          echo "Executing: $MIHOMO_BIN convert-ruleset domain yaml \"$INPUT_FILE\" \"$TEMP_OUTPUT_FILE\""
          
          "$MIHOMO_BIN" convert-ruleset \
            "domain" \
            "yaml" \
            "$INPUT_FILE" \
            "$TEMP_OUTPUT_FILE"
          
          if [ $? -ne 0 ]; then
            echo "Mihomo conversion failed!"
            exit 1
          fi
          
          echo "Mihomo conversion completed successfully. Generated temporary file: $TEMP_OUTPUT_FILE"
          ls -l "$TEMP_OUTPUT_DIR"

          mv "$TEMP_OUTPUT_FILE" "${{ github.workspace }}/privateDomain.mrs"
          echo "Moved privateDomain.mrs to repository root."

      - name: Setup Target Repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}  # 其他仓库的访问令牌
        run: |
          # 配置目标仓库信息
          TARGET_REPO_OWNER="zhstzzy"
          TARGET_REPO_NAME="mihomo-rule"
          TARGET_BRANCH="main"  # 目标仓库的分支名
          
          # 克隆目标仓库
          git clone "https://$TARGET_REPO_TOKEN@github.com/$TARGET_REPO_OWNER/$TARGET_REPO_NAME.git" target-repo
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 切换到目标分支
          git checkout $TARGET_BRANCH || git checkout -b $TARGET_BRANCH
          cd ..

      - name: Copy MRS to Target Repository
        run: |
          # 将生成的MRS文件复制到目标仓库目录
          cp "${{ github.workspace }}/privateDomain.mrs" "target-repo/privateDomain.mrs"
          echo "Copied MRS file to target repository directory"

      - name: Commit and Push to Target Repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          cd target-repo
          
          # 检查文件是否有变化
          if git diff --quiet --exit-code; then
            echo "No changes detected in target repository. Skipping commit."
          else
            # 提交并推送到目标仓库
            git add privateDomain.mrs
            git commit -m "chore: Auto-update privateDomain.mrs [skip ci]"
            git push origin HEAD:$TARGET_BRANCH
            echo "Successfully pushed to target repository"
          fi
